#!/bin/sh
# get changed files (Added, Changed, Modified)
# sed for retaining space
FILES=$(git diff --staged --name-only --diff-filter=ACM | sed 's| |\\ |g')
# exit if no FILES found
[ -z "$FILES" ] && exit 0
#echo "Added/Changed/Modified files are"
#echo $FILES
#echo ==========================PRETTIER=========================================
echo "$FILES" | parallel prettier --ignore-unknown --write
#exec 1>&2
#echo $(pwd)
#echo ==========================ISORT=========================================
echo "$FILES" | grep -i ".py" | parallel isort
#isort "$FILES"
#echo ==========================BLACK=========================================
echo "$FILES" | grep -i ".py" | parallel black
#black "$FILES"
#echo ==========================READY=========================================
# Add back the modified/prettified files to staging
echo "$FILES" | parallel git add
# Clean end
exit 0